Neighbourhood/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hoodapp.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hoodapp/urls.py
from django.urls import path
from . import views

app_name ='hood'
urlpatterns =[
    path('',views.home,name='home'),
    path('register/',views.Register_user,name='register'),
    path('login/',views.Login_view,name='login'),
    path('logout/',views.Logout_view,name='logout'),
    path('profile/',views.Profile,name='profile'),
    path('business/',views.Business_view,name='business'),
    path('updates/',views.Updates_view,name='updates'),
    path('search/',views.Search_data,name='search'),
    
       
]

hoodapp/models.py
from time import time
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q


# Create your models here.

class Location(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        
        return self.name
    
    
    def save_location(self):
        self.save()
    
    
class Category(models.Model):
    category_name = models.CharField(max_length=80,null=False,blank=False)
    def __str__(self):
    
        return self.category_name
    
    def save_category(self):
        self.save()


class Neighbourhood(models.Model):
    name = models.CharField(max_length=255)
    location = models.ForeignKey(Location,on_delete=models.CASCADE,blank=True)
    occupants_count = models.IntegerField(default=0,blank=True,null=True)
    police_num = models.CharField(max_length=255,null=True,blank=True)
    hospital_num = models.CharField(max_length=255,null=True,blank=True)
    def __str__(self):
        
        return self.name
    
    def create_neigbourhood(self):
        self.save()

    @classmethod
    def delete_neigbourhood(cls, id):
        cls.objects.filter(id=id).delete()

    @classmethod
    def find_neigbourhood(cls, searchterm):
        search_results = cls.objects.filter(Q(name__icontains=searchterm))
        return search_results

    @classmethod
    def update_neighbourhood(cls, id, name):
        cls.objects.filter(id=id).update(name=name)
    
    
class Business(models.Model):
    
    name = models.CharField(max_length=255)    
    email_address = models.EmailField(max_length=255)
    neighbourhood = models.ForeignKey(Neighbourhood,on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=1000)
    image = models.ImageField(default='business.jpg',upload_to='bizimages', blank=True)
    posted = models.DateTimeField(auto_now_add=True, blank=True)
    def __str__(self):
        
        return self.name
    
    def save_business(self):
        self.save()

    @classmethod
    def delete_business(cls, id): 
        cls.objects.filter(id=id).delete()

    @classmethod
    def searchbusiness(cls, searchterm):
        search_results = cls.objects.filter(Q(name__icontains = searchterm))
        return search_results
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.IntegerField(null=True, blank=True)
    bio = models.TextField(max_length=1500,null=True,blank=True)
    avatar = models.ImageField(default='avatar.jpg',upload_to='profiles')
    neighbourhood = models.ForeignKey(Neighbourhood,on_delete=models.CASCADE,blank=True,null=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, blank=True,null=True) 
    def __str__(self):
        return f'{self.user.username} Profile'  
    
    

        
class Hood_update(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000,null=False, blank=False)
    author = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    neighbourhood = models.ForeignKey(Neighbourhood,on_delete=models.CASCADE,blank=True,null=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=False,blank=False)
    image = models.ImageField(default='business.jpg',upload_to='bizimages', blank=True)
    
    def __str__(self):
        
        return self.title
    
    def save_update(self):
        self.save()

    @classmethod
    def delete_update(cls, id):
        cls.objects.filter(id=id).delete()
  
            
    
    
    

    

hoodapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile

# register form

class Register_Form(UserCreationForm):
    
    
    class Meta:
        model = User
        fields =['first_name','username', 'email', 'password1', 'password2']


class UserForm(forms.ModelForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    class Meta:
        model = User
        fields = ('username', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
       model = Profile
       fields = '__all__'
       exclude = ['username']      

hoodapp/views.py
from .forms import *
from django.shortcuts import render,redirect
from .models import *
from django.contrib.auth.decorators import login_required

from django.contrib import messages
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.models import User





# Create your views here.
def home(request):
    
    return render(request, 'hood/home.html')

def Updates_view(request):
    
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        author = request.user
        neighbourhood = request.user.profile.neighbourhood
        category = request.POST.get('category')
        image = request.FILES.get('upload')
        print(category)
        post = Hood_update.objects.create(title=title, description=description, author=author, neighbourhood = neighbourhood,category=category, image=image)
        
    if request.user.profile.neighbourhood is None:
        messages.warning(request, 'Please update Neighbourhood to view updates or business')
        return redirect('hood:profile')
    else:
        stories = Hood_update.objects.filter(category__category_name='Announcements',
            neighbourhood=request.user.profile.neighbourhood)
        
        alerts = Hood_update.objects.filter(category__category_name='Alerts',
            neighbourhood=request.user.profile.neighbourhood)
        
        events = Hood_update.objects.filter(category__category_name='Events',
        neighbourhood=request.user.profile.neighbourhood)
    
    neibdetails = Neighbourhood.objects.get(
            name=request.user.profile.neighbourhood)
    categories = Category.objects.all() 
    
    context = {
        'stories': stories,
        'alerts': alerts,
        'events': events,
        'neibdetails': neibdetails,
        'categories': categories
        }
    
    return render(request, 'hood/updates.html',context)

@login_required(login_url='hood:login') 
def Business_view(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email_address = request.POST.get('email_address')
        neighbourhood = request.user.profile.neighbourhood
        author = request.user
        description = request.POST.get('description')
        image = request.FILES.get('upload')
        biz = Business.objects.create(name=name,email_address=email_address,neighbourhood=neighbourhood,author=author,description=description,image=image)
    
    if request.user.profile.neighbourhood is None:
        messages.warning(request, 'Please update Neighbourhood to view updates or business')

        return redirect('hood:profile')
    else:
        
        business = Business.objects.filter(
            neighbourhood=request.user.profile.neighbourhood)
    neibdetails = Neighbourhood.objects.get(
            name=request.user.profile.neighbourhood)
    category = Category.objects.all()
    count=User.objects.all().count()
    context = {
        'business': business,
        'category': category,
        'neibdetails': neibdetails,
        'count':count,
        
    }
    return render(request, 'hood/business.html',context)


def Neighbourhood_view(request):
    
    neighbourhood = Neighbourhood.objects.all()
    
    context = {
        'neighbourhood': neighbourhood
    }
    
    
    return render(request, 'hoodapp/neighbourhood.html',context)


def Search_data(req):
    
    if req.method=='GET':
        search_site = req.GET.get("search")
        if search_site:
            search= Business.objects.filter(Q(name__icontains=search_site)|Q(author__username__icontains=search_site))
            print(search_site)
            return render(req, 'hood/search.html', {'search':search})
            
        





# AUTHENTICATION SECTION

def Register_user(request):
    form = Register_Form()
    
    if request.method == 'POST':
        form = Register_Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('hood:profile')
    
    context={
        'form': form,
    }
    return render(request,'accounts/register.html',context)



def Login_view(request):
    if request.method == 'POST':
    
    
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect('hood:home')
            
        else:
            # Return an 'invalid login' error message.
            messages.warning(request, 'Username or password is incorrect')
        
        

    return render(request,'accounts/login.html')


def Logout_view(request):
    logout(request)
    return redirect('hood:home')
    # Redirect to a success page.
    
    
    
@login_required(login_url='hood:login')  
def Profile(request):
    if request.method == 'POST':
        u_form = UserForm(request.POST, instance=request.user)
        p_form = ProfileForm(request.POST,request.FILES, instance=request.user.profile)
        
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Account updated!')
            return redirect('hood:home')

    else:
        u_form = UserForm(instance=request.user)
        p_form = ProfileForm(instance=request.user.profile)
        # current_profile = Profile.objects.get(user_id = request.user)
        # current_post = Post.user_post(request.user) 
    
    userdata = Business.objects.filter(author = request.user)
    context = {
       'u_form': u_form,
       'p_form': p_form,
       'userdata': userdata,
       
        
    }
    
    return render(request, 'accounts/profile.html',context)

        
            
    
        
        

hoodapp/templates/hood/base.html
{% load bootstrap5 %}
{% load static%}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">

 
  <title>Home {{title}}</title>
  

  {% block styles %}
  {% bootstrap_css %}

  <link rel="stylesheet" href="{% static 'css/home.css' %}">
  {% endblock %}

</head>
<body>
  <nav>
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'hood:business' %}">Business</a></li>
        <li><a href="{% url 'hood:updates' %}">Updates</a></li>
        <li><a href="">Contact</a></li>
    </ul>
</nav>
<a href="{% url 'hood:login' %}">
<button class="btn" id="btn1">Log In</button>

</a>

<a href="{% url 'hood:register' %}">
    
<button class="btn" id="btn2">Sign Up</button>

</a>

</div>
    {% block content %}  </h1> {%endblock%}

    {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
     {% bootstrap_javascript %}
    {% endblock %}
</body>
</html>

hoodapp/templates/hood/business.html
{% extends 'hood/layout.html' %} 

{% block content%}


      
<div class="container-fluid">
  
  <div class="row px-1 py-4">
    <div class="col-md-2">
      
      <div class="card" style="width: 18rem;">
        <div class="card-header bg-info">
          <h3 class="text-white w-bold">{{neibdetails.name}}</h3>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><span class="iconify" data-icon="bxs:contact" style="color: #64cc90;" data-width="22" data-height="22"></span>~{{neibdetails.hospital_num}}</li>
          <li class="list-group-item"><span class="iconify" data-icon="bxs:contact" style="color: #64cc90;" data-width="22" data-height="22"></span>~{{neibdetails.police_num}}</li>
          <li class="list-group-item"><span class="iconify" data-icon="fluent:people-community-add-28-filled" style="color: #64cc90;" data-width="22" data-height="22"></span>~ {{count}} occupants</li>


        </ul>
        <a class="btn btn-success btn-block btn-md " href="" data-bs-toggle="modal" data-bs-target="#biz">Add business</a>

      </div>
        <div class="py-4">
        <div class="card" style="width: 18rem;">
          <div class="card-header">
          <h3>Neighbourhood updates</h3>
          </div>
          <ul class="list-group list-group-flush " id="ul">
            <li class="list-group-item">
                <a href="{% url 'hood:updates' %}" id="links">All</a>
            </li>
            {% for category in category %}
            <li class="list-group-item">
                <a href="">{{category.category_name}}</a>
            </li>

            {% endfor %}
         
        
            
            

          </ul>
        </div>
      </div>
     </div>
     

     <div class="col-md-10">
      <div class="row px-4">
        {% for business in business %}
        <div class="col-md-6 d-flex py-4">
          <div class="imgsec">
            <img src="{{business.image.url}}" alt="" srcset="">
          </div>
          <div class="desc px-4">
            <h3>{{business.name}}</h3>
            <p><span class="iconify" data-icon="carbon:location-filled" style="color: #64cc90;" data-width="20" data-height="20"></span>~<strong>{{business.neighbourhood}}</strong></p>

            <p>{{business.description}}</p>
            <p><span class="iconify" data-icon="ic:round-email" style="color: #64cc90;" data-width="20" data-height="20"></span>~<strong style="font-style: italic;">{{business.email_address}}</strong></p>

            <a href="">
              <button class="btn1" type="submit">View</button>
            </a>
          </div>
          
        </div>
        {% empty %}

        <div>
          <h3>no businesses posted yet</h3>
        </div>
        
      
        {% endfor %}
        
      </div>
     </div>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="biz" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Post Business</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <label for="">Business name:</label>
          <input class="form-control" type="text" name="name" id="name" placeholder="name">
          <label for="">Business email:</label>
          <input class="form-control" type="email" name="email_address" id="email_address" placeholder="email address" required>
          <label for="">Business description:</label>
          <input class="form-control" type="text" name="description" id="description" placeholder="description" required>
          <br>
          <label for="">Image:</label>
          <input type="file" class="form-control me-2" name="upload" id="upload">
          <br>
          <button class="btn btn-success" type="submit">Post</button>

        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>
    
{% endblock  %}

hoodapp/templates/hood/home.html
{% load static%}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="{% static 'hoodcss/home.css' %}?{% now "U" %}" type="text/css">

    <title>Home</title>
</head>
<body>
    <div class="cont">
    <div class="container-fluid" id="cont">
        
        <div class="header">
            <img src="https://thumbs.dreamstime.com/b/modern-home-logo-design-concept-modern-home-logo-design-concept-172472928.jpg" class="logo">
            <nav>
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="{% url 'hood:business' %}">Business</a></li>
                    <li><a href="{% url 'hood:updates' %}">Updates</a></li>
                   
                </ul>
            </nav>
           

                {% if request.user.is_authenticated %}
        
                <div class="dropdown" style="margin-right: 150px;">
                  <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <span class="text-white w-bold py-2">{{user.username}}</span>
                    <img src="{{user.profile.avatar.url}}" style="object-fit: cover;" alt="" width="40" height="40"
                      class="rounded-circle">
                  </a>
                  <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                
                    <li><a class="dropdown-item" href="{% url 'hood:profile'%}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'hood:logout'%}">Log out</a></li>
                  </ul>
                </div>
               

           
           
            {% else %}
             <a href="{% url 'hood:login'%}">
                <button class="btn" id="btn1">Log In</button>
    
                </a>
                <a href="{% url 'hood:register'%}">
                <button class="btn" id="btn2">Sign Up</button>
    
                </a>

            {% endif %}
            
        </div>
        <div class="content">
            <div class="text">
            <h1>HOODVILLE</h1>
            <p>"There is no power for change greater than a community discovering what it cares about." <br>– Margaret J. Wheatley
            </p>
            <a href="{% url 'hood:business' %}">
            <button class="btn3">Explore</button>


            </a>
           </div>
       
       </div>
   </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>    
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>    

</body>
</html>

{% endblock %}

hoodapp/templates/hood/layout.html
{% load static%}
{% load bootstrap5 %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'hoodcss/style.css' %}?{% now "U" %}" type="text/css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'hood:home' %}">HOOD</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
           
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hood:business' %}">Business</a>
            </li>
          
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hood:updates' %}">Updates</a>
            </li>
           
          </ul>
          <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'hood:search' %}">
            <input class="form-control mr-sm-2" type="search" name="search" id="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
      
      {% block content %}

      {% endblock %}
  
      

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>    
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>    
<script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>         
</body>
</html>

hoodapp/templates/hood/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'hood:home' %}">HOOD</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      
    
          
      
      <li><a href="">Updates</a></li>
      <li><a href="">Contact</a></li>
    </ul>

   
    <ul class="nav navbar-nav navbar-right">
      <li><a href=""><span class="glyphicon glyphicon-user"></span> </a></li>
      <li><a href=""><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
  


</body>
</html>

hoodapp/templates/hood/search.html
{% extends 'hood/layout.html' %} 

{% block content%}

<div class="container my-5">
  
     <div class="row d-flex justify-content-center">
         
         <hr>
      
         <div class="col-md-9">
              <div class="row">
                 {% for data in search %}
                  <div class="col-md-4">
                    <div class="imgsec">
                      <img src="{{data.image.url}}" alt="" srcset="">
                    </div>
                    <div class="desc px-4">
                      <h3>{{data.name}}</h3>
                      <p><span class="iconify" data-icon="carbon:location-filled" style="color: #64cc90;" data-width="20" data-height="20"></span>~<strong>{{data.neighbourhood}}</strong></p>
          
                      <p>{{data.description}}</p>
                      <p><span class="iconify" data-icon="ic:round-email" style="color: #64cc90;" data-width="20" data-height="20"></span>~<strong style="font-style: italic;">{{data.email_address}}</strong></p>
          
                      <a href="">
                        <button class="btn1" type="submit">View</button>
                      </a>
                    </div>
                     
                  </div>
                  {% empty %}
                  <h1>nodata</h1>
                  {% endfor %}
                  
                
                  
              </div>
         </div>
     </div> 
  </div>
   
{% endblock %}

hoodapp/templates/hood/updates.html
{% extends 'hood/layout.html' %} 

{% block content%}

 
   


      
<div class="container-fluid" id="main">
  
  <div class="row px-1 py-4">
    <div class="col-md-1">

    </div>
    <div class="col-md-2">
      
      <div class="card" style="width: 18rem;">
        <div class="card-header bg-info">
          <h3 class="text-white w-bold">{{neibdetails.name}}</h3>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><span class="iconify" data-icon="bxs:contact" style="color: #64cc90;" data-width="22" data-height="22"></span>~{{neibdetails.hospital_num}}</li>
          <li class="list-group-item"><span class="iconify" data-icon="bxs:contact" style="color: #64cc90;" data-width="22" data-height="22"></span>~{{neibdetails.police_num}}</li>

        </ul>

          <a href="" class="px-4 py-3" data-bs-toggle="modal" data-bs-target="#post">
            <button class="btn22" type="submit"><span class="iconify" data-icon="ant-design:plus-outlined" data-width="25" data-height="25"></span>
              Post</button>

          </a>        

      </div>
     </div>

     
     

     <div class="col-md-3 card" id="cardstory">
      <div class="row">
        {% for story in stories %}
        <div>
         <div class="str">
          <div class="author d-flex py-2 px-3">
          <img class="authorimg" src="{{story.author.profile.avatar.url}}" alt="">
          <p class="px-1 py-1">
            <strong>{{story.author.username}}</strong>
          </p>

          </div>

          
          
         </div>
         <div class="storysec px-3">
          <img src="{{story.image.url}}" alt="" srcset="">
          <h5>{{story.title}}</h5>

          <p>{{story.description | truncatewords:10}}</p>
         </div>
          
        </div>
        {% empty %}

        <div>
          <h3>no announcements</h3>
        </div>
        
      
        {% endfor %}
        
      </div>
     </div>
     

     <div class="col-md-3 px-4">
      
      <div class="card" style="width: 25rem;background-color: #F7F7F7;">
        <div class="card-header bg-info">
          <h3 class="text-white w-bold">Upcoming events</h3>
          
        </div>
        {% for event in events %}
        <div class="events px-3 py-2">
          <div class="card" id="event">
            <div class="div px-2 py-2">
              <span>
                <span class="iconify" data-icon="ci:dot-04-l" style="color: #9826ab;" data-width="30" data-height="30"></span>10:00-11:00
              </span>
              <p>
                <strong>{{event.description}}</strong>
                
              </p>

            </div>
           
            

          </div>
        </div>
        {% empty %}

        <div>
          <h3>no events</h3>
        </div>
        
        {% endfor %}
       

      </div>
      
        <div class="py-4">
        <div class="card" style="width: 25rem;">
          <div class="card-header">
          <h3>Alerts</h3>
          </div>
          {% for alert in alerts %}
          <div class="events px-3 py-2">
            <div class="card" id="event">
              <div class="div px-2 py-2">
                <span>
                  <strong>{{alert.title}}</strong>
                </span>
                <p>
                  {{alert.description | truncatewords:6}}
                  
                </p>
  
              </div>
             
              
  
            </div>
          </div>
          {% empty %}

          <div>
            <h3>no alerts</h3>
          </div>
          {% endfor %}
          
        </div>
      </div>
     </div>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="post" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Post update</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <label for="">Title:</label>
          <input type="text" class="form-control" name="title" id="title" placeholder="Enter title" required>

          <label for="">Description:</label>
          <input type="text" class="form-control" name="description" id="description" placeholder="Enter description" required><br>
          
          <div class="form-group m-3">
            <label>Select a category</label>
            <select name="category" class="form-control">
                <option value="none">Select category...</option>
                {% for category in categories %}
                <option value="{{category.category_name }}">{{  category.category_name }}</option>



                {% endfor %}
            </select>
          </div>
          <br>
          <label for="">Image:</label>
          <input type="file" class="form-control" name="upload" id="upload">
          <br>
          <button class="btn btn-success" type="submit">Post</button>
          
          
        </form>
      </div>
      
    </div>
  </div>
</div>



   
{% endblock %}